- name: "unarchive backend"
  unarchive:
    src: artifact.tar.gz
    dest: /home/ubuntu/

- name: "executing node"
  shell: |
    cd /home/ubuntu/backend/
    npm install
    pm2 stop default
    pm2 start npm -- start
